export type SingleStageFlags = {
  urls?: string[];
  urlFile?: string;
  search?: string;
  searchSort?: string;
  outDir?: string;
  keyframes?: string;
  jobs?: string;
  subLangs?: string;
  sceneThreshold?: string;
  sceneMinGap?: string;
  maxWords?: string;
  cookiesFromBrowser?: string;
  proxy?: string;
  platform?: string;
  maxChars?: string;
  rewriteMode?: string;
  targets?: string;
  target?: string;
  threadSource?: string;
  publishDryRun?: boolean;
  dryRun?: boolean;
  thread?: boolean;
  publishMaxChars?: string;
  maxTweets?: string;
  threadDelay?: string;
  numbering?: boolean;
  continueFrom?: boolean;
  errorStrategy?: string;
  force?: boolean;
  mode?: string;
  llmProvider?: string;
  llmModel?: string;
  llmBaseUrl?: string;
  verbose?: boolean;
};

export type SingleStageTarget = "acquire" | "notes" | "article" | "publish";
