export {
  clearTechnicalTermDiscoveryCaches,
  createFileTechnicalTermDiscoveryCacheStore,
  discoverTechnicalTerms,
  getCachedTechnicalTermDiscovery,
  repairTechnicalTermViolations,
  technicalTermDiscoveryAuditFor,
  technicalTermDiscoveryCacheFilePath,
  technicalTermDiscoveryCacheKeyFor,
  technicalTermDiscoverySourceIdentityFor,
  fingerprintTechnicalTermDiscoverySource,
  type DiscoverTechnicalTermsInput,
  type RepairTechnicalTermViolationsInput,
  type TechnicalTermDiscoveryResult,
} from "./discovery.js";
